Repository memorisecodead/ChitChat, pull requests merged in 2023-11, with the labels that each got.

#14 Cover Network tests
  .github/workflows/Clang Linux Build.yml
  .github/workflows/GCC Linux Build.yml
  .github/workflows/GCC Sonar Linux Build.yml
  .github/workflows/Windows Build.yml
  CMakeLists.txt
  Network/CMakeLists.txt
  Network/HTTPSession.hpp
  Network/WebSocket.hpp
  Tests/NetworkTests/CMakeLists.txt
  Tests/NetworkTests/NetworkTest.cpp
  cmake/ConanModule.cmake
  cmake/Coverage.cmake
  sonar-project.properties
Labels: Tests, Back

#18 Cleaning smells
  Tests/NetworkTests/NetworkTest.cpp
Labels: bug, Back

#19 Network Refactoring
  Main/main.cpp
  Network/BeastAttribute.hpp
  Network/CMakeLists.txt
  Network/HTTPSession.hpp
  Network/Listener.hpp
  Network/ListenerConfig.hpp
  Network/WebSocket.hpp
  Tests/NetworkTests/NetworkTest.cpp
Labels: documentation, Technical debt, Back

#21 Doxygen base
  Doxyfile
Labels: documentation, Technical debt
